import os
import subprocess
import json
import csv
from pathlib import Path
from tree_sitter import Language, Parser
from datetime import datetime
import re

# ==== CONFIG ====
JAVA_LANG = Language(
    "/home/yixuan/Documents/master/processor/tree-sitter-langs/build/my-languages.so",
    "java"
)

OUTPUT_JSON = "combined_comments.json"
OUTPUT_CSV = "combined_comments.csv"
HUMAN_CUTOFF = datetime(2021, 6, 1)

# AI detection patterns
AI_KEYWORDS = ["copilot", "auto-generated","auto-gen", "gpt", "llm", "generated by ai"]
DASH_PATTERN = re.compile(r"[-=]{3,}")  # --- or === lines
EMOJI_PATTERN = re.compile(r"[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF"
                           r"\U0001F680-\U0001F6FF\U0001F1E0-\U0001F1FF]")

# ==== HELPER CLASSES ====
class CommentRecord:
    def __init__(self, repo, file_path, class_name, comment_text, level, start_line, end_line,
                 commit_hash, commit_date, commit_message, label):
        self.repo = repo
        self.file_path = file_path
        self.class_name = class_name
        self.comment_text = comment_text
        self.level = level
        self.start_line = start_line
        self.end_line = end_line
        self.commit_hash = commit_hash
        self.commit_date = commit_date
        self.commit_message = commit_message
        self.label = label

    def to_dict(self):
        return {
            "repo": self.repo,
            "file_path": self.file_path,
            "class_name": self.class_name,
            "comment_text": self.comment_text,
            "level": self.level,
            "start_line": self.start_line,
            "end_line": self.end_line,
            "commit_hash": self.commit_hash,
            "commit_date": self.commit_date,
            "commit_message": self.commit_message,
            "label": self.label
        }

# ==== FUNCTIONS ====
def find_all_java_files(root_path):
    return [str(p) for p in Path(root_path).rglob("*.java")]

def get_last_commit(file_path, repo_path):
    rel_path = os.path.relpath(file_path, repo_path)
    try:
        cmd = ["git", "-C", repo_path, "log", "-1", "--pretty=format:%H|%ad|%s", "--date=iso", "--", rel_path]
        out = subprocess.check_output(cmd, universal_newlines=True).strip()
        if out:
            parts = out.split("|", 2)
            if len(parts) == 3:
                return parts[0], parts[1], parts[2]
    except subprocess.CalledProcessError:
        pass
    return None, None, None

def determine_label(commit_date_str, comment_text):
    # Start with date-based label
    if not commit_date_str:
        label = "unknown"
    else:
        try:
            commit_dt = datetime.fromisoformat(commit_date_str.split(" ")[0])
            label = "human" if commit_dt < HUMAN_CUTOFF else "unknown"
        except Exception:
            label = "unknown"

    # Override if AI patterns detected
    lower_text = comment_text.lower()
    if any(k in lower_text for k in AI_KEYWORDS):
        label = "artificial_intelligence"
    elif DASH_PATTERN.search(comment_text):
        label = "artificial_intelligence"
    elif EMOJI_PATTERN.search(comment_text):
        label = "artificial_intelligence"

    return label

def determine_label_debug(commit_date_str, comment_text):
    """
    Determine label and return both label and reason.
    """
    reason = None
    # Start with date-based label
    if not commit_date_str:
        label = "unknown"
        reason = "no_commit_date"
    else:
        try:
            commit_dt = datetime.fromisoformat(commit_date_str.split(" ")[0])
            label = "human" if commit_dt < HUMAN_CUTOFF else "unknown"
            reason = "date_based"
        except Exception:
            label = "unknown"
            reason = "date_parse_failed"

    # Check for AI heuristics
    lower_text = comment_text.lower()
    ai_rule_triggered = None

    # Keywords
    for keyword in AI_KEYWORDS:
        if re.search(rf"\b{re.escape(keyword)}\b", lower_text):
            label = "artificial_intelligence"
            ai_rule_triggered = f"keyword:{keyword}"
            break

    # Dash lines
    if not ai_rule_triggered and DASH_PATTERN.search(comment_text):
        label = "artificial_intelligence"
        ai_rule_triggered = "dash_line"

    # Emojis
    if not ai_rule_triggered and EMOJI_PATTERN.search(comment_text):
        label = "artificial_intelligence"
        ai_rule_triggered = "emoji"

    if ai_rule_triggered:
        reason = f"ai_rule_triggered:{ai_rule_triggered}"

    return label, reason


def extract_class_comments(file_path):
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            source = f.read()
    except Exception as e:
        print(f"⚠️  Cannot read file {file_path}: {e}")
        return []

    parser = Parser()
    parser.set_language(JAVA_LANG)
    tree = parser.parse(bytes(source, "utf8"))

    comments = []
    def recurse(node):
        if node.type == "block_comment":
            sibling = node.next_named_sibling
            class_name = None
            level = "inline"
            if sibling and sibling.type == "class_declaration":
                for c in sibling.children:
                    if c.type == "identifier":
                        class_name = source[c.start_byte:c.end_byte]
                        break
                level = "class"
            if level == "class":
                start_line = node.start_point[0] + 1
                end_line = node.end_point[0] + 1
                comments.append((class_name, node.text.decode("utf-8", errors="ignore"), level, start_line, end_line))
        for child in node.children:
            recurse(child)

    recurse(tree.root_node)
    return comments

# ... keep all your imports and configs unchanged ...

CHUNK_SIZE = 5000  # number of comments per chunk
LABELED_JSON = "labeled_comments.json"
LABELED_CSV = "labeled_comments.csv"

def save_results(records, json_path, csv_path):
    with open(json_path, "w", encoding="utf-8") as f_json:
        json.dump([r.to_dict() for r in records], f_json, indent=2)
    with open(csv_path, "w", encoding="utf-8", newline="") as f_csv:
        writer = csv.DictWriter(f_csv, fieldnames=list(records[0].to_dict().keys()) if records else [])
        writer.writeheader()
        for r in records:
            writer.writerow(r.to_dict())
    print(f"Saved results: {json_path} + {csv_path}")

# ==== UPDATED FUNCTIONS ====
def process_repo(repo_path, repo_name):
    print(f"🔹 Processing repo: {repo_name}")
    records = []
    all_files = find_all_java_files(repo_path)
    for idx, file_path in enumerate(all_files, 1):
        print(f"  [{idx}/{len(all_files)}] {file_path}")
        comments = extract_class_comments(file_path)
        commit_hash, commit_date, commit_msg = get_last_commit(file_path, repo_path)
        for class_name, comment_text, level, start_line, end_line in comments:
            label, reason = determine_label_debug(commit_date, comment_text)
            rec = CommentRecord(
                repo_name, os.path.relpath(file_path, repo_path),
                class_name, comment_text, level, start_line, end_line,
                commit_hash, commit_date, commit_msg, label
            )
            # Add debug info
            rec.debug_reason = reason
            records.append(rec)
    print(f"Extracted {len(records)} class-level comments from {repo_name}\n")
    return records

def save_chunks(records, base_name="combined_comments", chunk_size=CHUNK_SIZE):
    for i in range(0, len(records), chunk_size):
        chunk = records[i:i+chunk_size]
        chunk_idx = i // chunk_size + 1
        json_path = f"{base_name}_{chunk_idx}.json"
        csv_path = f"{base_name}_{chunk_idx}.csv"
        save_results(chunk, json_path, csv_path)

def save_labeled(records, json_path=LABELED_JSON, csv_path=LABELED_CSV):
    labeled_records = [r for r in records if r.label in ("human", "artificial_intelligence")]
    save_results(labeled_records, json_path, csv_path)
    print(f"Saved labeled human + AI comments: {json_path} + {csv_path}")


# ==== MAIN ====
if __name__ == "__main__":
    repo_list = [
        ("/home/yixuan/Documents/master/spring-framework", "spring-framework"),
        ("/home/yixuan/Documents/master/guava", "guava"),
        ("/home/yixuan/Documents/master/processor", "processor")
    ]

    all_records = []
    for repo_path, repo_name in repo_list:
        all_records.extend(process_repo(repo_path, repo_name))

    # Save all combined comments in chunks
    save_chunks(all_records, base_name="combined_comments", chunk_size=CHUNK_SIZE)

    # Save human + AI comments
    save_labeled(all_records)

